---
# Source: nifi-registry/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: RELEASE-NAME-nifi-registry
  labels:
    helm.sh/chart: nifi-registry-0.1.1
    app.kubernetes.io/name: nifi-registry
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "0.6.0"
    app.kubernetes.io/managed-by: Helm
