# Default values for ca.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: apache/nifi-toolkit
  pullPolicy: IfNotPresent
  tag: "1.13.2"

service:
  type: ClusterIP
  port: 9090

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  enabled: true
  storageClass: managed-premium
  # The default storage class is used if this variable is not set.
  accessModes:  [ReadWriteOnce]

  ## Storage Capacities for persistent volumes
  # Storage capacity for the 'data' directory, which is used to hold things such as the flow.xml.gz, configuration, state, etc.
  caStorage:
    size: 10Gi
  manual: false
  nfs:
    storageClass: "nfs"
    # full path will be //xxnfsxxx/databaseflow-storage01..02.., need to be created at advance
    pathPrefix: "//xxxnfsxxx/nifi-ca"
    server: "xxxnfsxxx.file.core.windows.net"


resources:
  requests:
    memory: "250Mi"
    cpu: "0.1"

app_port: 9090

token: sixteenCharacters

securityContext:
  fsGroup: 1000
  runAsUser: 1000

serviceAccount:
  create: false
  #name: nifi-ca

## Openshift support
## Use the following varables in order to enable Route and Security Context Constraint creation
openshift:
  scc:
    enabled: true
