{{- if .Values.openshift.scc.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:scc:{{ template "apache-nifi.fullname" . }}-scc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:{{ template "apache-nifi.fullname" . }}-scc
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ include "apache-nifi.serviceAccountName" . }}
{{- end }}
