{{- if .Values.openshift.networkpolicy.enabled -}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-same-namespace-and-ingress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  ingress:
  - from:
    - podSelector: {}
    - namespaceSelector:
        matchLabels:
          network.openshift.io/policy-group: ingress
{{- end }}
